### ISSUE TITLE
Address errors resulting from running the test suite

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#425]
# User Story

As a BEARS **operator**, in order to **verify that code is ready for deployment**, I would like **any remaining errors to be addressed** .

Running `npm test` returns a passing result and it says all tests pass... but it also spits out three errors.

The site still works and everything seems to be fine... but there are three errors that look like they ought to be resolved.  My concern is that if these error messages are, in fact, indicating that something is wrong and we deploy anyways, we run the risk of stuff breaking, potentially in an untimely or urgent situation.

Here's a recent run of the `test` action that runs `npm test`:

https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:1

The text of the errors is also included here.

## Error 1: this.$refs.accordion.focus is not a function

```
● Console

    console.error
      [Vue warn]: Error in nextTick: "TypeError: this.$refs.accordion.focus is not a function"
      
      found in
      
      ---> <LifeEvent>
             <Root>

      at warn (node_modules/vue/dist/vue.common.dev.js:630:15)
      at logError (node_modules/vue/dist/vue.common.dev.js:1898:5)
      at globalHandleError (node_modules/vue/dist/vue.common.dev.js:1893:3)
      at handleError (node_modules/vue/dist/vue.common.dev.js:1853:5)
      at Array.<anonymous> (node_modules/vue/dist/vue.common.dev.js:1996:9)
      at flushCallbacks (node_modules/vue/dist/vue.common.dev.js:1920:14)

    console.error
      TypeError: this.$refs.accordion.focus is not a function
          at VueComponent.<anonymous> (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/pages/_lifeEvent.vue:375:1)
          at Array.<anonymous> (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/vue/dist/vue.common.dev.js:1994:[12](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:12))
          at flushCallbacks (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/vue/dist/vue.common.dev.js:1920:14)

      at logError (node_modules/vue/dist/vue.common.dev.js:1902:[13](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:13))
      at globalHandleError (node_modules/vue/dist/vue.common.dev.js:1893:3)
      at handleError (node_modules/vue/dist/vue.common.dev.js:1853:5)
      at Array.<anonymous> (node_modules/vue/dist/vue.common.dev.js:1996:9)
      at flushCallbacks (node_modules/vue/dist/vue.common.dev.js:1920:[14](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:14))
```

## Error 2: date-fns doesn't accept strings as date arguments

```
● Console

    console.warn
      Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule

      [45](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:45) |     return null
      46 |   }
    > 47 |   userInputDate = toDate(userInputDate)
         |                   ^
      48 |   const dateData = [userInputDate.getFullYear(), userInputDate.getMonth(), userInputDate.getDate()]
      49 |   return isExists(...dateData)
      50 | }

      at toDate (node_modules/date-fns/toDate/index.js:54:15)
      at checkSelectedAndExists (services/dateHelper.js:47:19)
      at validateDateAgainstAcceptance (services/dateHelper.js:9:26)
      at Object.<anonymous> (test/service/dateHelper.spec.js:205:17)

    console.warn
      Error: 
          at toDate (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/date-fns/toDate/index.js:56:20)
          at checkSelectedAndExists (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/services/dateHelper.js:47:19)
          at validateDateAgainstAcceptance (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/services/dateHelper.js:9:26)
          at Object.<anonymous> (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/test/service/dateHelper.spec.js:205:17)
          at Promise.then.completed (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/utils.js:391:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/utils.js:316:10)
          at _callCircusTest (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/run.js:218:40)
          at _runTest (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/run.js:155:3)
          at _runTestsForDescribeBlock (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/run.js:66:9)
          at _runTestsForDescribeBlock (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/run.js:60:9)
          at run (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/run.js:25:3)
          at runAndTransformResultsToJestFormat (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
          at jestAdapter (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
          at runTestInternal (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-runner/build/runTest.js:389:16)
          at runTest (/home/runner/work/usagov-benefits-eligibility/usagov-benefits-eligibility/node_modules/jest-runner/build/runTest.js:475:34)

      45 |     return null
      [46](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:46) |   }
    > [47](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:47) |   userInputDate = toDate(userInputDate)
         |                   ^
      [48](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:48) |   const dateData = [userInputDate.getFullYear(), userInputDate.getMonth(), userInputDate.getDate()]
      [49](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:49) |   return isExists(...dateData)
      [50](https://github.com/GSA/usagov-benefits-eligibility/runs/6414728297?check_suite_focus=true#step:5:50) | }

      at toDate (node_modules/date-fns/toDate/index.js:56:15)
      at checkSelectedAndExists (services/dateHelper.js:47:19)
      at validateDateAgainstAcceptance (services/dateHelper.js:9:26)
      at Object.<anonymous> (test/service/dateHelper.spec.js:205:17)
```

## Error 3: Missing required prop: "cards"

```
 ● Console

    console.error
      [Vue warn]: Missing required prop: "cards"
      
      found in
      
      ---> <CrossSell>
             <Root>

      at warn (node_modules/vue/dist/vue.common.dev.js:630:15)
      at assertProp (node_modules/vue/dist/vue.common.dev.js:1686:5)
      at validateProp (node_modules/vue/dist/vue.common.dev.js:1637:5)
      at loop (node_modules/vue/dist/vue.common.dev.js:4673:17)
      at initProps (node_modules/vue/dist/vue.common.dev.js:4704:33)
      at initState (node_modules/vue/dist/vue.common.dev.js:4647:21)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.common.dev.js:5010:5)
      at new VueComponent (node_modules/vue/dist/vue.common.dev.js:5157:12)

```

Acceptance Criteria:

- [ ] error 1 goes away
- [ ] error 2 goes away
- [ ] error 3 goes away

Definition of Done:

- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Build process and deployment is automated and repeatable
- [ ] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved

**Comment by lgarceau768** [comment]
Also I just fixed the third error by removing the required tag.
